name: akshaya_flutter
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  http: ^1.2.2
  intl: ^0.19.0
  connectivity: ^3.0.6
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.10+1
  dio: ^5.6.0
  fluttertoast: ^8.2.8
  flutter_spinkit: ^5.2.1
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^3.0.0






flutter:

  
  
  
  uses-material-design: true

  

  assets:
      - assets/ic_logo.png
      - assets/appbg.png
      - assets/ic_user.png
      - assets/ic_home.svg
      - assets/ic_my.svg
      - assets/ic_request.svg
      - assets/ic_myprofile.svg
      - assets/ic_care.svg
      - assets/ic_user.png
      - assets/ffb_collection.png
      - assets/passbook.png
      - assets/main_visit.png
      - assets/fertilizers.png
      - assets/equipment.png
      - assets/labour.png
      - assets/quick_pay.png
      - assets/visit.png
      - assets/loan.png
      - assets/fertilizers_1.png
      - assets/harvesting.png
      - assets/pest.png
      - assets/oilpalm.png
      - assets/general.png
      - assets/ic_lernin.png
      - assets/fertilizers.png
      - assets/fertilizers.png
      - assets/ic_left.png
      - assets/ic_bank_white.png
      - assets/ic_calender.png
  
  

  
  

  
  
  
  
  
  fonts:

    - family: hind
      fonts:
        - asset: fonts/hind_semibold.ttf
  
  
  
  
  
  
  
  
  
  
  
  
  
  
