name: akshaya_flutter
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  carousel_slider: ^5.0.0
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.6
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^2.3.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  go_router: ^14.2.6
  http: ^1.2.2
  intl: ^0.19.0
  marquee: ^2.2.3
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.2
  qrscan: ^0.3.3
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

flutter_gen:
  output: lib/gen/
  line_length: 80
  package_parameter_enabled: true
  directory_path_enabled: true

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: hind
      fonts:
        - asset: fonts/hind_semibold.ttf
